### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Lucky-069** [n00byara/NotificationCode#1]
The app is unable to install on Android 11.
Please add support for android 11 too.

**Comment by n00byara** [comment]
I downgrade min version to android 11. But I can not guarantee stable work on Android 11 because I use Android 13.
I also recommend using lsposed to run the application(I using it). Non-root support was added exclusively for users who are unable to install lsposed.
<a href="https://github.com/n00byara/NotificationCode/releases/tag/v3.0.4">Release</a>
